
all:

clean:

romfs:
	$(ROMFSINST) /usr/bin/adbyby.sh
	$(ROMFSINST) /usr/bin/adbchk.sh
	$(ROMFSINST) /etc_ro/7620n.tar.gz
	$(ROMFSINST) /etc_ro/koolproxy.tar.gz
	$(ROMFSINST) /www/Advanced_adbyby.asp