/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux ubuntu 4.10.0-20-generic #22-Ubuntu SMP Thu Apr 20 09:22:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux"
#define BUILD_ENV_DATE "Sat May 27 08:59:52 PDT 2017"
#define BUILD_ENV_SRCDIR "/opt/newifi/trunk/user/samba3/source"
#define BUILD_ENV_BUILDDIR "/opt/newifi/trunk/user/samba3/source"
#define BUILD_ENV_USER "root"
#define BUILD_ENV_HOST "ubuntu"
#define BUILD_ENV_COMPILER "/opt/newifi/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc-gcc"
#endif /* _BUILD_ENV_H */
